# Generated by Django 5.2.4 on 2026-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_anomaly_expense_is_auto_categorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_ml_predicted',
            field=models.BooleanField(default=False),
        ),
    ]
